### ISSUE TITLE
MC crashes when both Inca and Sodium are used

### ISSUE THREAD

**Issue by calloatti** [tyra314/Inca#10]
MC 1.16.1

inca-1.2.1.jar

https://github.com/jellysquid3/sodium-fabric/releases/tag/mc1.16.1-0.1.0

Crash log: https://paste.ee/p/4oNzN

Comment on sodium discord: "you're using a mod that expects the Fabric Rendering API"

**Comment by bluebear94** [comment]
I can [reproduce this](https://paste.ee/p/Ufmq4) with only the offending mods (plus Fabric API).

**Comment by Sunconure11** [comment]
I'm noticing I straight up crash with this combo.

https://pastebin.com/EKfZRfqX

**Comment by tyra314** [comment]
> Comment on sodium discord: "you're using a mod that expects the Fabric Rendering API"

That's not true. The cause is clashing Mixins. Both mods define a Mixin for `WorldRenderer.class`, which incidentally define a member variable with the same name. I guess that's the reason everyone insists on prefixing the names with the mod id or some other stuff :( 

Thus, this is a bug in both mods.

Fixed in 97ce9c3018e0fa2f697eca6e4e511d49325c3f23
